require('./jquery.min.js');
global.$ = global.jQuery = require('jquery');
require('./bootstrap.bundle.min.js');
global.Cookies = require('./js.cookie.js');
require('./jquery.scrollbar.min.js');
require('./jquery-scrollLock.min.js');
global.moment = require('./moment.js');
require('./Chart.min.js');
require('./Chart.extension.js');
require('./argon.js');